object Form1: TForm1
  Left = 0
  Top = 0
  BorderStyle = bsSingle
  Caption = 'Form1'
  ClientHeight = 637
  ClientWidth = 545
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object pnlContainer: TPanel
    Left = 0
    Top = 0
    Width = 545
    Height = 637
    Align = alClient
    TabOrder = 0
    object pnlHeader: TPanel
      Left = 1
      Top = 1
      Width = 543
      Height = 112
      Align = alTop
      Caption = 'pnlHeader'
      TabOrder = 0
      object Shape1: TShape
        AlignWithMargins = True
        Left = 11
        Top = 11
        Width = 521
        Height = 64
        Margins.Left = 10
        Margins.Top = 10
        Margins.Right = 10
        Margins.Bottom = 10
        Align = alTop
        Shape = stRoundRect
        ExplicitLeft = 18
        ExplicitTop = 12
      end
      object btnDoItSerch: TButton
        Left = 11
        Top = 79
        Width = 102
        Height = 25
        Caption = 'Realizar Pesquisa'
        TabOrder = 0
        OnClick = btnDoItSerchClick
      end
      object edCNPJ: TEdit
        Left = 97
        Top = 22
        Width = 336
        Height = 43
        Alignment = taCenter
        BorderStyle = bsNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -37
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        Text = '03.560.235/0006-30'
      end
    end
    object pnlInformations: TPanel
      Left = 1
      Top = 113
      Width = 543
      Height = 523
      Align = alClient
      Padding.Left = 5
      Padding.Top = 5
      Padding.Right = 5
      Padding.Bottom = 5
      TabOrder = 1
      object pnlLastUpdate: TPanel
        Left = 6
        Top = 6
        Width = 531
        Height = 51
        Align = alTop
        TabOrder = 0
        object pnlLastUpdateData: TPanel
          AlignWithMargins = True
          Left = 11
          Top = 27
          Width = 519
          Height = 23
          Margins.Left = 10
          Margins.Top = 0
          Margins.Right = 0
          Margins.Bottom = 0
          Align = alClient
          Alignment = taLeftJustify
          BevelOuter = bvNone
          TabOrder = 0
        end
        object pnlLastUpdateLine: TPanel
          Left = 1
          Top = 25
          Width = 529
          Height = 2
          Margins.Top = 0
          Margins.Right = 0
          Margins.Bottom = 0
          Align = alTop
          BevelOuter = bvNone
          Caption = 'pnlLastUpdateLine'
          Color = clBackground
          ParentBackground = False
          TabOrder = 1
        end
        object pnlLastUpdateText: TPanel
          AlignWithMargins = True
          Left = 11
          Top = 1
          Width = 519
          Height = 24
          Margins.Left = 10
          Margins.Top = 0
          Margins.Right = 0
          Margins.Bottom = 0
          Align = alTop
          Alignment = taLeftJustify
          BevelOuter = bvNone
          Caption = #218'ltima Atualiza'#231#227'o'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 2
        end
      end
      object pnlReasonSituation: TPanel
        AlignWithMargins = True
        Left = 6
        Top = 454
        Width = 531
        Height = 51
        Margins.Left = 0
        Margins.Top = 5
        Margins.Right = 0
        Margins.Bottom = 0
        Align = alTop
        TabOrder = 1
        object pnlReasonSituationLine: TPanel
          Left = 1
          Top = 25
          Width = 529
          Height = 2
          Margins.Top = 0
          Margins.Right = 0
          Margins.Bottom = 0
          Align = alTop
          BevelOuter = bvNone
          Caption = 'pnlDataSituationLine'
          Color = clBackground
          ParentBackground = False
          TabOrder = 0
        end
        object pnlReasonSituationText: TPanel
          AlignWithMargins = True
          Left = 11
          Top = 1
          Width = 519
          Height = 24
          Margins.Left = 10
          Margins.Top = 0
          Margins.Right = 0
          Margins.Bottom = 0
          Align = alTop
          Alignment = taLeftJustify
          BevelOuter = bvNone
          Caption = 'Motivo da Situa'#231#227'o Cadastral'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 1
        end
        object pnlReasonSituationData: TPanel
          Left = 1
          Top = 27
          Width = 529
          Height = 23
          Margins.Left = 10
          Margins.Top = 0
          Margins.Right = 0
          Margins.Bottom = 0
          Align = alClient
          Alignment = taLeftJustify
          BevelOuter = bvNone
          Color = clInfoBk
          Padding.Left = 10
          ParentBackground = False
          TabOrder = 2
        end
      end
      object Panel4: TPanel
        AlignWithMargins = True
        Left = 6
        Top = 398
        Width = 531
        Height = 51
        Margins.Left = 0
        Margins.Top = 5
        Margins.Right = 0
        Margins.Bottom = 0
        Align = alTop
        TabOrder = 2
        object pnlSituation: TPanel
          Left = 1
          Top = 1
          Width = 329
          Height = 49
          Align = alLeft
          TabOrder = 0
          object pnlSituationData: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 27
            Width = 317
            Height = 21
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alClient
            Alignment = taLeftJustify
            BevelOuter = bvNone
            TabOrder = 0
          end
          object pnlSituationLine: TPanel
            Left = 1
            Top = 25
            Width = 327
            Height = 2
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            BevelOuter = bvNone
            Caption = 'pnlLastUpdateLine'
            Color = clBackground
            ParentBackground = False
            TabOrder = 1
          end
          object pnlSituationText: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 1
            Width = 317
            Height = 24
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            Alignment = taLeftJustify
            BevelOuter = bvNone
            Caption = 'Situa'#231#227'o Cadastral'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
            TabOrder = 2
          end
        end
        object pnlDateSituation: TPanel
          Left = 330
          Top = 1
          Width = 200
          Height = 49
          Align = alClient
          TabOrder = 1
          object pnlDateSituationData: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 27
            Width = 188
            Height = 21
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alClient
            Alignment = taLeftJustify
            BevelOuter = bvNone
            TabOrder = 0
          end
          object pnlDataSituationLine: TPanel
            Left = 1
            Top = 25
            Width = 198
            Height = 2
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            BevelOuter = bvNone
            Caption = 'pnlDataSituationLine'
            Color = clBackground
            ParentBackground = False
            TabOrder = 1
          end
          object pnlDataSituationText: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 1
            Width = 188
            Height = 24
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            Alignment = taLeftJustify
            BevelOuter = bvNone
            Caption = 'Data da Situa'#231#227'o Cadastral'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
            TabOrder = 2
          end
        end
      end
      object pnlContact: TPanel
        AlignWithMargins = True
        Left = 6
        Top = 342
        Width = 531
        Height = 51
        Margins.Left = 0
        Margins.Top = 5
        Margins.Right = 0
        Margins.Bottom = 0
        Align = alTop
        TabOrder = 3
        object pnlContactTelephone: TPanel
          Left = 265
          Top = 1
          Width = 265
          Height = 49
          Align = alClient
          TabOrder = 0
          object pnlContactTelephoneData: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 27
            Width = 253
            Height = 21
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alClient
            Alignment = taLeftJustify
            BevelOuter = bvNone
            TabOrder = 0
          end
          object pnlContactTelephoneLine: TPanel
            Left = 1
            Top = 25
            Width = 263
            Height = 2
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            BevelOuter = bvNone
            Caption = 'pnlLastUpdateLine'
            Color = clBackground
            ParentBackground = False
            TabOrder = 1
          end
          object pnlContactTelephoneText: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 1
            Width = 253
            Height = 24
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            Alignment = taLeftJustify
            BevelOuter = bvNone
            Caption = 'Telefone'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
            TabOrder = 2
          end
        end
        object pnlContactEmail: TPanel
          Left = 1
          Top = 1
          Width = 264
          Height = 49
          Align = alLeft
          TabOrder = 1
          object pnlContactEmailData: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 27
            Width = 252
            Height = 21
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alClient
            Alignment = taLeftJustify
            BevelOuter = bvNone
            TabOrder = 0
          end
          object pnlContactLine: TPanel
            Left = 1
            Top = 25
            Width = 262
            Height = 2
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            BevelOuter = bvNone
            Caption = 'pnlLastUpdateLine'
            Color = clBackground
            ParentBackground = False
            TabOrder = 1
          end
          object pnlContactEmailText: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 1
            Width = 252
            Height = 24
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            Alignment = taLeftJustify
            BevelOuter = bvNone
            Caption = 'Endere'#231'o Eletr'#244'nico'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
            TabOrder = 2
          end
        end
      end
      object pnlAddressInformations: TPanel
        AlignWithMargins = True
        Left = 6
        Top = 286
        Width = 531
        Height = 51
        Margins.Left = 0
        Margins.Top = 5
        Margins.Right = 0
        Margins.Bottom = 0
        Align = alTop
        TabOrder = 4
        object pnlUF: TPanel
          Left = 417
          Top = 1
          Width = 113
          Height = 49
          Align = alClient
          TabOrder = 0
          object pnlUFText: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 1
            Width = 101
            Height = 24
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            Alignment = taLeftJustify
            BevelOuter = bvNone
            Caption = 'UF'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
            TabOrder = 0
          end
          object pnlUFLine: TPanel
            Left = 1
            Top = 25
            Width = 111
            Height = 2
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            BevelOuter = bvNone
            Caption = 'pnlLastUpdateLine'
            Color = clBackground
            ParentBackground = False
            TabOrder = 1
          end
          object pnlUFData: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 27
            Width = 101
            Height = 21
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alClient
            Alignment = taLeftJustify
            BevelOuter = bvNone
            TabOrder = 2
          end
        end
        object pnlCity: TPanel
          Left = 265
          Top = 1
          Width = 152
          Height = 49
          Align = alLeft
          TabOrder = 1
          object pnlCityText: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 1
            Width = 140
            Height = 24
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            Alignment = taLeftJustify
            BevelOuter = bvNone
            Caption = 'Munic'#237'pio'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
            TabOrder = 0
          end
          object pnlCityLine: TPanel
            Left = 1
            Top = 25
            Width = 150
            Height = 2
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            BevelOuter = bvNone
            Caption = 'pnlLastUpdateLine'
            Color = clBackground
            ParentBackground = False
            TabOrder = 1
          end
          object pnlCityData: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 27
            Width = 140
            Height = 21
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alClient
            Alignment = taLeftJustify
            BevelOuter = bvNone
            TabOrder = 2
          end
        end
        object pnlBairro: TPanel
          Left = 121
          Top = 1
          Width = 144
          Height = 49
          Align = alLeft
          TabOrder = 2
          object pnlBairroText: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 1
            Width = 132
            Height = 24
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            Alignment = taLeftJustify
            BevelOuter = bvNone
            Caption = 'Bairro'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
            TabOrder = 0
          end
          object pnlBairroline: TPanel
            Left = 1
            Top = 25
            Width = 142
            Height = 2
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            BevelOuter = bvNone
            Caption = 'pnlLastUpdateLine'
            Color = clBackground
            ParentBackground = False
            TabOrder = 1
          end
          object pnlBairroData: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 27
            Width = 132
            Height = 21
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alClient
            Alignment = taLeftJustify
            BevelOuter = bvNone
            TabOrder = 2
          end
        end
        object pnlCEP: TPanel
          Left = 1
          Top = 1
          Width = 120
          Height = 49
          Align = alLeft
          TabOrder = 3
          object pnlCEPText: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 1
            Width = 108
            Height = 24
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            Alignment = taLeftJustify
            BevelOuter = bvNone
            Caption = 'CEP'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
            TabOrder = 0
          end
          object pnlCEPLine: TPanel
            Left = 1
            Top = 25
            Width = 118
            Height = 2
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            BevelOuter = bvNone
            Caption = 'pnlLastUpdateLine'
            Color = clBackground
            ParentBackground = False
            TabOrder = 1
          end
          object pnlCEPData: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 27
            Width = 108
            Height = 21
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alClient
            Alignment = taLeftJustify
            BevelOuter = bvNone
            TabOrder = 2
          end
        end
      end
      object pnlAddress: TPanel
        AlignWithMargins = True
        Left = 6
        Top = 230
        Width = 531
        Height = 51
        Margins.Left = 0
        Margins.Top = 5
        Margins.Right = 0
        Margins.Bottom = 0
        Align = alTop
        TabOrder = 5
        object pnlComplet: TPanel
          Left = 378
          Top = 1
          Width = 152
          Height = 49
          Align = alClient
          TabOrder = 0
          object pnlCompletData: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 27
            Width = 140
            Height = 21
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alClient
            Alignment = taLeftJustify
            BevelOuter = bvNone
            TabOrder = 0
          end
          object pnlCompletLine: TPanel
            Left = 1
            Top = 25
            Width = 150
            Height = 2
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            BevelOuter = bvNone
            Caption = 'pnlLastUpdateLine'
            Color = clBackground
            ParentBackground = False
            TabOrder = 1
          end
          object pnlCompletText: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 1
            Width = 140
            Height = 24
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            Alignment = taLeftJustify
            BevelOuter = bvNone
            Caption = 'Complemento'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
            TabOrder = 2
          end
        end
        object pnlAddressNumber: TPanel
          Left = 265
          Top = 1
          Width = 113
          Height = 49
          Align = alLeft
          TabOrder = 1
          object pnlAddressNumberData: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 27
            Width = 101
            Height = 21
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alClient
            Alignment = taLeftJustify
            BevelOuter = bvNone
            TabOrder = 0
          end
          object pnlAddressNumberLine: TPanel
            Left = 1
            Top = 25
            Width = 111
            Height = 2
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            BevelOuter = bvNone
            Caption = 'pnlLastUpdateLine'
            Color = clBackground
            ParentBackground = False
            TabOrder = 1
          end
          object pnlAddressNumberText: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 1
            Width = 101
            Height = 24
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            Alignment = taLeftJustify
            BevelOuter = bvNone
            Caption = 'N'#250'mero'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
            TabOrder = 2
          end
        end
        object pnlAddressStreet: TPanel
          Left = 1
          Top = 1
          Width = 264
          Height = 49
          Align = alLeft
          TabOrder = 2
          object pnlAddressStreetData: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 27
            Width = 252
            Height = 21
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alClient
            Alignment = taLeftJustify
            BevelOuter = bvNone
            TabOrder = 0
          end
          object pnlAddressStreetLine: TPanel
            Left = 1
            Top = 25
            Width = 262
            Height = 2
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            BevelOuter = bvNone
            Caption = 'pnlLastUpdateLine'
            Color = clBackground
            ParentBackground = False
            TabOrder = 1
          end
          object pnlAddressStreetText: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 1
            Width = 252
            Height = 24
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            Alignment = taLeftJustify
            BevelOuter = bvNone
            Caption = 'Logradouro'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
            TabOrder = 2
          end
        end
      end
      object pnlNatJuridica: TPanel
        AlignWithMargins = True
        Left = 6
        Top = 174
        Width = 531
        Height = 51
        Margins.Left = 0
        Margins.Top = 5
        Margins.Right = 0
        Margins.Bottom = 0
        Align = alTop
        TabOrder = 6
        object pnlNatJuridicaData: TPanel
          AlignWithMargins = True
          Left = 11
          Top = 27
          Width = 519
          Height = 23
          Margins.Left = 10
          Margins.Top = 0
          Margins.Right = 0
          Margins.Bottom = 0
          Align = alClient
          Alignment = taLeftJustify
          BevelOuter = bvNone
          TabOrder = 0
        end
        object pnlNatJuridicaLine: TPanel
          Left = 1
          Top = 25
          Width = 529
          Height = 2
          Margins.Top = 0
          Margins.Right = 0
          Margins.Bottom = 0
          Align = alTop
          BevelOuter = bvNone
          Caption = 'pnlLastUpdateLine'
          Color = clBackground
          ParentBackground = False
          TabOrder = 1
        end
        object pnlNatJuridicaText: TPanel
          AlignWithMargins = True
          Left = 11
          Top = 1
          Width = 519
          Height = 24
          Margins.Left = 10
          Margins.Top = 0
          Margins.Right = 0
          Margins.Bottom = 0
          Align = alTop
          Alignment = taLeftJustify
          BevelOuter = bvNone
          Caption = 'C'#243'digo e Descri'#231#227'o da Natureza Jur'#237'dica'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 2
        end
      end
      object pnlName: TPanel
        AlignWithMargins = True
        Left = 6
        Top = 118
        Width = 531
        Height = 51
        Margins.Left = 0
        Margins.Top = 5
        Margins.Right = 0
        Margins.Bottom = 0
        Align = alTop
        TabOrder = 7
        object pnlnameText: TPanel
          AlignWithMargins = True
          Left = 11
          Top = 1
          Width = 519
          Height = 24
          Margins.Left = 10
          Margins.Top = 0
          Margins.Right = 0
          Margins.Bottom = 0
          Align = alTop
          Alignment = taLeftJustify
          BevelOuter = bvNone
          Caption = 'Nome Empresarial'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
        object pnlNameLine: TPanel
          Left = 1
          Top = 25
          Width = 529
          Height = 2
          Margins.Top = 0
          Margins.Right = 0
          Margins.Bottom = 0
          Align = alTop
          BevelOuter = bvNone
          Caption = 'pnlLastUpdateLine'
          Color = clBackground
          ParentBackground = False
          TabOrder = 1
        end
        object pnlNameData: TPanel
          AlignWithMargins = True
          Left = 11
          Top = 27
          Width = 519
          Height = 23
          Margins.Left = 10
          Margins.Top = 0
          Margins.Right = 0
          Margins.Bottom = 0
          Align = alClient
          Alignment = taLeftJustify
          BevelOuter = bvNone
          TabOrder = 2
        end
      end
      object pnlNumberAndDate: TPanel
        AlignWithMargins = True
        Left = 6
        Top = 62
        Width = 531
        Height = 51
        Margins.Left = 0
        Margins.Top = 5
        Margins.Right = 0
        Margins.Bottom = 0
        Align = alTop
        TabOrder = 8
        object pnlNumber: TPanel
          Left = 1
          Top = 1
          Width = 336
          Height = 49
          Align = alLeft
          TabOrder = 0
          object pnlCNPJText: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 1
            Width = 324
            Height = 24
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            Alignment = taLeftJustify
            BevelOuter = bvNone
            Caption = 'N'#250'mero de Inscri'#231#227'o'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
            TabOrder = 0
          end
          object pnlCNPJLine: TPanel
            Left = 1
            Top = 25
            Width = 334
            Height = 2
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            BevelOuter = bvNone
            Caption = 'pnlLastUpdateLine'
            Color = clBackground
            ParentBackground = False
            TabOrder = 1
          end
          object PnlCNPJData: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 27
            Width = 324
            Height = 21
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alClient
            Alignment = taLeftJustify
            BevelOuter = bvNone
            TabOrder = 2
          end
        end
        object pnlDateOpen: TPanel
          Left = 337
          Top = 1
          Width = 193
          Height = 49
          Align = alClient
          TabOrder = 1
          object pnlDateOpenText: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 1
            Width = 181
            Height = 24
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            Alignment = taLeftJustify
            BevelOuter = bvNone
            Caption = 'Data de Abertura'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
            TabOrder = 0
          end
          object pnlDateOpenLine: TPanel
            Left = 1
            Top = 25
            Width = 191
            Height = 2
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alTop
            BevelOuter = bvNone
            Caption = 'pnlLastUpdateLine'
            Color = clBackground
            ParentBackground = False
            TabOrder = 1
          end
          object pnlDateOpenData: TPanel
            AlignWithMargins = True
            Left = 11
            Top = 27
            Width = 181
            Height = 21
            Margins.Left = 10
            Margins.Top = 0
            Margins.Right = 0
            Margins.Bottom = 0
            Align = alClient
            Alignment = taLeftJustify
            BevelOuter = bvNone
            TabOrder = 2
          end
        end
      end
    end
  end
  object Panel1: TPanel
    Left = 19
    Top = 13
    Width = 73
    Height = 16
    Alignment = taLeftJustify
    BevelOuter = bvNone
    Caption = 'Digite o CNPJ'
    Color = clWhite
    ParentBackground = False
    TabOrder = 1
  end
end
